// <auto-generated />
namespace Data_Access.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_block : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_block));
        
        string IMigrationMetadata.Id
        {
            get { return "202112221236113_add_block"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
