// <auto-generated />
namespace Data_Access.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class create_postView : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create_postView));
        
        string IMigrationMetadata.Id
        {
            get { return "202112251056356_create_postView"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
