// <auto-generated />
namespace Data_Access.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig_views : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_views));
        
        string IMigrationMetadata.Id
        {
            get { return "202112251733290_mig_views"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
